# Generated by Django 3.2.9 on 2022-03-02 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandprofile',
            old_name='Position',
            new_name='position',
        ),
    ]
