# Generated by Django 3.2.9 on 2022-03-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_rename_position_brandprofile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='email',
            field=models.EmailField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='company',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='first_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='position',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='tel',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
