# Generated by Django 3.2.9 on 2022-04-28 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_brandprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
