# Generated by Django 3.2.9 on 2022-08-21 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0016_auto_20220821_1909'),
        ('shouters', '0011_auto_20220316_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('shouter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shouters.shouter')),
            ],
        ),
    ]
