# Generated by Django 3.2.9 on 2022-08-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0002_selection_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
