# Generated by Django 3.2.9 on 2022-08-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0003_selection_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='cpr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
