# Generated by Django 3.2.9 on 2022-08-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0004_selection_cpr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='price',
            new_name='brand_price',
        ),
        migrations.AddField(
            model_name='selection',
            name='shouter_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
