# Generated by Django 3.2.9 on 2022-04-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cal_cpr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cal_estimate_reach',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cal_number_shouter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_is_fb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_is_ig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_is_tiktok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_is_twitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_work_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
