# Generated by Django 3.2.9 on 2022-04-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20220428_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='cal_estimate_reach',
            new_name='cal_estimate_reach_max',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='cal_number_shouter',
            new_name='cal_estimate_reach_min',
        ),
        migrations.AddField(
            model_name='campaign',
            name='cal_number_shouter_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cal_number_shouter_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
