# Generated by Django 3.2.9 on 2022-04-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20220428_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='cal_cpr',
            new_name='cal_cpr_max',
        ),
        migrations.AddField(
            model_name='campaign',
            name='cal_cpr_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
