# Generated by Django 3.2.9 on 2022-05-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_alter_campaign_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_content_type_post',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_content_type_story',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
