# Generated by Django 3.2.9 on 2022-05-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_auto_20220503_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='cal_cpr_max',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='cal_cpr_min',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='cal_estimate_reach_max',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='cal_estimate_reach_min',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='cal_number_shouter_max',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='cal_number_shouter_min',
        ),
        migrations.AddField(
            model_name='campaign',
            name='calculate_dict',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='calculate_dict_fb',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
