# Generated by Django 3.2.9 on 2022-05-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_auto_20220511_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_fc_story_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
