# Generated by Django 3.2.9 on 2022-05-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_campaign_campaign_fc_story_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='calculate_dict',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='calculate_dict_fb',
        ),
        migrations.AddField(
            model_name='campaign',
            name='estimate_max_cpr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='estimate_max_reach',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='estimate_max_shouter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='estimate_min_cpr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='estimate_min_reach',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='estimate_min_shouter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='estimate_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
