# Generated by Django 3.2.9 on 2022-08-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_auto_20220525_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_fc_story_count',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='estimate_time',
        ),
        migrations.AddField(
            model_name='campaign',
            name='product_detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='product_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='product_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='campaign',
            name='product_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='campaign',
            name='product_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
