# Generated by Django 3.2.9 on 2022-08-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_auto_20220818_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='product_photo_1',
            field=models.ImageField(blank=True, upload_to='campaign/product/'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='product_photo_2',
            field=models.ImageField(blank=True, upload_to='campaign/product/'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='product_photo_3',
            field=models.ImageField(blank=True, upload_to='campaign/product/'),
        ),
    ]
