# Generated by Django 3.2.9 on 2022-08-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_auto_20220818_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='product_photo_1',
            field=models.ImageField(blank=True, default=None, upload_to='campaign/product/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='product_photo_2',
            field=models.ImageField(blank=True, default=None, upload_to='campaign/product/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='product_photo_3',
            field=models.ImageField(blank=True, default=None, upload_to='campaign/product/'),
            preserve_default=False,
        ),
    ]
