# Generated by Django 3.2.9 on 2022-08-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_auto_20220821_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
