# Generated by Django 3.2.9 on 2022-08-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_campaign_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_phase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
