# Generated by Django 3.2.9 on 2022-08-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0019_alter_campaign_campaign_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='brief_caption',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='brief_detail',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='brief_photo',
            field=models.ImageField(blank=True, null=True, upload_to='campaign/brief/photo/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='brief_ref_photo',
            field=models.ImageField(blank=True, null=True, upload_to='campaign/brief/photo/'),
        ),
    ]
