# Generated by Django 3.2.9 on 2022-08-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_auto_20220830_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='operation_photo',
            field=models.ImageField(blank=True, null=True, upload_to='campaign/operation/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='service_detail',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='shouter_post_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
