# Generated by Django 3.2.9 on 2022-08-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_auto_20220830_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='service_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
