# Generated by Django 3.2.9 on 2021-12-06 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_register', models.BooleanField(default=False)),
                ('line_access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('line_access_token_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('line_id_token', models.CharField(blank=True, max_length=500, null=True)),
                ('line_id_token_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('line_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('line_username', models.CharField(blank=True, max_length=100, null=True)),
                ('line_profile_picture', models.URLField(blank=True, max_length=500, null=True)),
                ('fb_access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('fb_access_token_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('fb_page_id', models.CharField(blank=True, max_length=120, null=True)),
                ('fb_is_connect', models.BooleanField(default=False)),
                ('ig_business_account_id', models.CharField(blank=True, max_length=120, null=True)),
                ('ig_username', models.CharField(blank=True, max_length=120, null=True)),
                ('ig_media_count', models.IntegerField(blank=True, null=True)),
                ('ig_follower_count', models.IntegerField(blank=True, null=True)),
                ('ig_following_count', models.IntegerField(blank=True, null=True)),
                ('ig_active_follower', models.IntegerField(blank=True, null=True)),
                ('ig_active_follower_harmonic', models.IntegerField(blank=True, null=True)),
                ('ig_active_follower_percent', models.FloatField(blank=True, null=True)),
                ('ig_estimated_reach', models.IntegerField(blank=True, null=True)),
                ('ig_profile_picture', models.URLField(blank=True, max_length=500, null=True)),
                ('ig_total_like', models.IntegerField(blank=True, null=True)),
                ('ig_average_total_like', models.IntegerField(blank=True, null=True)),
                ('ig_engagement_percent', models.FloatField(blank=True, null=True)),
                ('ig_story_view', models.FloatField(blank=True, null=True)),
                ('ig_average_post_reach', models.FloatField(blank=True, null=True)),
                ('ig_price_story_fc', models.FloatField(blank=True, null=True)),
                ('ig_price_story_ugc', models.FloatField(blank=True, null=True)),
                ('ig_price_post_fc', models.FloatField(blank=True, null=True)),
                ('ig_price_post_ugc', models.FloatField(blank=True, null=True)),
                ('ig_price_story_post_fc', models.FloatField(blank=True, null=True)),
                ('ig_price_story_post_ugc', models.FloatField(blank=True, null=True)),
                ('ig_insight', models.JSONField(blank=True, null=True)),
                ('ig_max_total_people', models.IntegerField(blank=True, null=True)),
                ('ig_two_most_common_city', models.JSONField(blank=True, null=True)),
                ('ig_two_most_common_country', models.JSONField(blank=True, null=True)),
                ('ig_two_most_common_gender_age', models.JSONField(blank=True, null=True)),
                ('ig_audience_male_percent', models.FloatField(blank=True, null=True)),
                ('ig_audience_female_percent', models.FloatField(blank=True, null=True)),
                ('ig_age_range_13_17', models.FloatField(blank=True, null=True)),
                ('ig_age_range_18_24', models.FloatField(blank=True, null=True)),
                ('ig_age_range_25_34', models.FloatField(blank=True, null=True)),
                ('ig_age_range_35_44', models.FloatField(blank=True, null=True)),
                ('ig_age_range_45_54', models.FloatField(blank=True, null=True)),
                ('ig_age_range_55_64', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
