# Generated by Django 3.2.9 on 2021-11-17 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_register', models.BooleanField(default=False)),
                ('is_connect_ig', models.BooleanField(default=False)),
                ('is_approve', models.BooleanField(default=False)),
                ('line_access_token', models.CharField(max_length=500)),
                ('line_access_token_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('line_id_token', models.CharField(max_length=500)),
                ('line_id_token_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('line_user_id', models.CharField(max_length=120)),
                ('line_username', models.CharField(max_length=120)),
                ('line_profile_picture', models.CharField(max_length=200)),
                ('fb_access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('fb_access_token_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('fb_page_id', models.CharField(blank=True, max_length=120, null=True)),
                ('ig_business_account_id', models.CharField(blank=True, max_length=120, null=True)),
                ('ig_username', models.CharField(blank=True, max_length=120, null=True)),
                ('ig_follower_count', models.IntegerField()),
                ('ig_active_follower', models.IntegerField()),
                ('ig_active_follower_harmonic', models.IntegerField()),
                ('ig_estimated_reach', models.IntegerField()),
                ('ig_total_like', models.IntegerField()),
                ('ig_average_total_like', models.IntegerField()),
                ('ig_like_engagement', models.IntegerField()),
                ('ig_insight', models.JSONField()),
                ('ig_max_total_people', models.IntegerField()),
                ('ig_two_most_common_city', models.JSONField()),
                ('ig_two_most_common_country', models.JSONField()),
                ('ig_two_most_common_gender_age', models.JSONField()),
                ('ig_audience_male_percent', models.FloatField()),
                ('ig_audience_female_percent', models.FloatField()),
                ('ig_age_range_13_17', models.FloatField()),
                ('ig_age_range_18_24', models.FloatField()),
                ('ig_age_range_25_34', models.FloatField()),
                ('ig_age_range_35_44', models.FloatField()),
                ('ig_age_range_45_54', models.FloatField()),
                ('ig_age_range_55_64', models.FloatField()),
            ],
        ),
    ]
