# Generated by Django 3.2.9 on 2021-12-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouter',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
