# Generated by Django 3.2.9 on 2021-11-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shouter',
            name='ig_active_follower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_active_follower_harmonic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_age_range_13_17',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_age_range_18_24',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_age_range_25_34',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_age_range_35_44',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_age_range_45_54',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_age_range_55_64',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_audience_female_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_audience_male_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_average_total_like',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_estimated_reach',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_follower_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_insight',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_like_engagement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_max_total_people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_total_like',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_two_most_common_city',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_two_most_common_country',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_two_most_common_gender_age',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
