# Generated by Django 3.2.9 on 2022-01-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouter',
            name='ig_ad_post_reach',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_predicted_ad_post_reach',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='is_finished_regis',
            field=models.BooleanField(default=False),
        ),
    ]
