# Generated by Django 3.2.9 on 2022-01-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0002_shouter_fb_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouter',
            name='fb_main_access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='fb_profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
