# Generated by Django 3.2.9 on 2022-01-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0002_auto_20220108_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shouter',
            name='ig_estimated_reach',
        ),
        migrations.RemoveField(
            model_name='shouter',
            name='ig_total_like',
        ),
    ]
