# Generated by Django 3.2.9 on 2021-12-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0002_shouter_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouter',
            name='is_connect_ig',
            field=models.BooleanField(default=False),
        ),
    ]
