# Generated by Django 3.2.9 on 2021-12-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0002_shouter_fb_is_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouter',
            name='ig_following_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_media_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_profile_picture',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
