# Generated by Django 3.2.9 on 2022-01-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0003_auto_20220109_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouter',
            name='fb_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
