# Generated by Django 3.2.9 on 2021-12-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0003_auto_20211201_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shouter',
            name='ig_like_engagement',
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_active_follower_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_engagement_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
