# Generated by Django 3.2.9 on 2021-12-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0003_shouter_is_connect_ig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shouter',
            old_name='is_connect_ig',
            new_name='is_approve',
        ),
    ]
