# Generated by Django 3.2.9 on 2022-01-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0004_auto_20220118_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouter',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='bank_username',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='is_connect_bank',
            field=models.BooleanField(default=False),
        ),
    ]
