# Generated by Django 3.2.9 on 2021-12-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0004_rename_is_connect_ig_shouter_is_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouter',
            name='is_already_approve',
            field=models.BooleanField(default=False),
        ),
    ]
