# Generated by Django 3.2.9 on 2021-12-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0004_auto_20211201_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouter',
            name='ig_average_post_reach',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_story_view',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
