# Generated by Django 3.2.9 on 2022-01-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0005_auto_20220118_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shouter',
            name='ig_price_post_fc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_price_post_ugc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_price_story_fc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_price_story_post_fc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_price_story_post_ugc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_price_story_ugc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
