# Generated by Django 3.2.9 on 2021-12-13 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0006_auto_20211213_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouter',
            name='register_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
