# Generated by Django 3.2.9 on 2021-12-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0006_auto_20211201_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouter',
            name='ig_price_story_post_fc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_price_story_post_ugc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
