# Generated by Django 3.2.9 on 2022-01-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0006_auto_20220121_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouter',
            name='is_refresh_shouters_data',
            field=models.BooleanField(default=False, verbose_name='REFRESH SHOUTER DATA'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='fb_access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='fb_is_connect',
            field=models.BooleanField(default=False, verbose_name='IS CONNECT TO FACEBOOK PAGE'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='fb_main_access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='fb_profile_picture',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_ad_post_reach',
            field=models.FloatField(blank=True, null=True, verbose_name='PREDICTED => AD POST REACH'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_average_post_reach',
            field=models.FloatField(blank=True, null=True, verbose_name='IG => AVERAGE POST REACH'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_average_total_like',
            field=models.IntegerField(blank=True, null=True, verbose_name='IG => AVERAGE LIKE'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_engagement_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='IG => LIKE PERCENTAGE'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_fb_price_post_fc',
            field=models.IntegerField(blank=True, null=True, verbose_name='IG+FB POST Price (MIN)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_fb_price_post_ugc',
            field=models.IntegerField(blank=True, null=True, verbose_name='IG+FB POST Price (MAX)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_fb_price_story_fc',
            field=models.IntegerField(blank=True, null=True, verbose_name='IG+FB STORY Price (MIN)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_fb_price_story_post_fc',
            field=models.IntegerField(blank=True, null=True, verbose_name='IG+FB STORY+POST Price (MIN)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_fb_price_story_post_ugc',
            field=models.IntegerField(blank=True, null=True, verbose_name='IG+FB STORY+POST Price (MAX)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_fb_price_story_ugc',
            field=models.IntegerField(blank=True, null=True, verbose_name='IG+FB STORY Price (MAX)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_predicted_ad_post_reach',
            field=models.FloatField(blank=True, null=True, verbose_name='PREDICTED => AVERAGE POST REACH'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_price_post_fc',
            field=models.IntegerField(blank=True, null=True, verbose_name='IG POST Price (MIN)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_price_post_ugc',
            field=models.IntegerField(blank=True, null=True, verbose_name='IG POST Price (MAX)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_price_story_fc',
            field=models.IntegerField(blank=True, null=True, verbose_name='IG STORY Price (MIN)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_price_story_post_fc',
            field=models.IntegerField(blank=True, null=True, verbose_name='IG STORY+POST Price (MIN)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_price_story_post_ugc',
            field=models.IntegerField(blank=True, null=True, verbose_name='IG STORY+POST Price (MAX)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_price_story_ugc',
            field=models.IntegerField(blank=True, null=True, verbose_name='IG STORY Price (MAX)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_profile_picture',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_story_view',
            field=models.FloatField(blank=True, null=True, verbose_name='IG => AVERAGE STORY VIEW'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_approve',
            field=models.BooleanField(default=False, verbose_name='IS ADMIN APPROVE'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_check_ig',
            field=models.BooleanField(default=False, verbose_name='ACCEPT WORK (IG)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_check_ig_fb',
            field=models.BooleanField(default=False, verbose_name='ACCEPT WORK (IG+FB)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_check_ig_fb_post',
            field=models.BooleanField(default=False, verbose_name='ACCEPT WORK (IG+FB => POST)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_check_ig_fb_story',
            field=models.BooleanField(default=False, verbose_name='ACCEPT WORK (IG+FB => STORY)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_check_ig_fb_story_post',
            field=models.BooleanField(default=False, verbose_name='ACCEPT WORK (IG+FB => STORY + POST)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_check_ig_post',
            field=models.BooleanField(default=False, verbose_name='ACCEPT WORK (IG => POST)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_check_ig_story',
            field=models.BooleanField(default=False, verbose_name='ACCEPT WORK (IG => STORY)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_check_ig_story_post',
            field=models.BooleanField(default=False, verbose_name='ACCEPT WORK (IG => STORY + POST)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_check_tiktok',
            field=models.BooleanField(default=False, verbose_name='ACCEPT WORK (TIKTOK)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_check_twitter',
            field=models.BooleanField(default=False, verbose_name='ACCEPT WORK (TWITTER)'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_connect_bank',
            field=models.BooleanField(default=False, verbose_name='IS CONNECT TO BANK'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_finished_regis',
            field=models.BooleanField(default=False, verbose_name='IS FINISHED REGISTRATION'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_register',
            field=models.BooleanField(default=False, verbose_name='IS COMPLETE PERSONAL INFO'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='line_access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='line_id_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='line_profile_picture',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='tiktok_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='TIKTOK NAME'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='tiktok_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='TIKTOK PRICE'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='twitter_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='TWITTER NAME'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='twitter_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='TWITTER PRICE'),
        ),
    ]
