# Generated by Django 3.2.9 on 2022-01-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0007_auto_20220131_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shouter',
            name='ig_ad_post_reach',
            field=models.IntegerField(blank=True, null=True, verbose_name='PREDICTED => AD POST REACH'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_average_post_reach',
            field=models.IntegerField(blank=True, null=True, verbose_name='IG => AVERAGE POST REACH'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_predicted_ad_post_reach',
            field=models.IntegerField(blank=True, null=True, verbose_name='PREDICTED => AVERAGE POST REACH'),
        ),
    ]
