# Generated by Django 3.2.9 on 2021-12-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0007_shouter_register_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouter',
            name='fb_response_business_account_id',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
