# Generated by Django 3.2.9 on 2021-12-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0008_shouter_fb_response_business_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouter',
            name='fb_response_access_token',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='fb_response_page_id',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_response_active_follower',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_response_audience_insight',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_response_bio',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_response_media_objects',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='interest',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
