# Generated by Django 3.2.9 on 2022-01-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0008_auto_20220131_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shouter',
            name='ig_story_view',
            field=models.IntegerField(blank=True, null=True, verbose_name='IG => AVERAGE STORY VIEW'),
        ),
    ]
