# Generated by Django 3.2.9 on 2022-02-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0009_alter_shouter_ig_story_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shouter',
            name='fb_access_token',
        ),
        migrations.RemoveField(
            model_name='shouter',
            name='fb_response_access_token',
        ),
        migrations.RemoveField(
            model_name='shouter',
            name='fb_response_business_account_id',
        ),
        migrations.RemoveField(
            model_name='shouter',
            name='fb_response_page_id',
        ),
        migrations.RemoveField(
            model_name='shouter',
            name='ig_response_bio',
        ),
        migrations.AddField(
            model_name='shouter',
            name='error_section',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='ERROR SECTION'),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_post_reach_guarantee',
            field=models.IntegerField(blank=True, null=True, verbose_name='GUARANTEE => POST REACH'),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_story_view_guarantee',
            field=models.IntegerField(blank=True, null=True, verbose_name='GUARANTEE => STORY VIEW'),
        ),
        migrations.AddField(
            model_name='shouter',
            name='is_error',
            field=models.BooleanField(default=False, verbose_name='SHOUTER IS ERROR'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_ad_post_reach',
            field=models.IntegerField(blank=True, null=True, verbose_name='ESTIMATE => AD POST REACH'),
        ),
    ]
