# Generated by Django 3.2.9 on 2021-12-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0010_auto_20211219_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouter',
            name='is_check_ig',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='is_check_ig_fb',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='is_check_tiktok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shouter',
            name='is_check_twitter',
            field=models.BooleanField(default=False),
        ),
    ]
