# Generated by Django 3.2.9 on 2022-08-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0011_auto_20220316_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shouter',
            name='ig_insight',
        ),
        migrations.RemoveField(
            model_name='shouter',
            name='ig_max_total_people',
        ),
        migrations.RemoveField(
            model_name='shouter',
            name='ig_two_most_common_city',
        ),
        migrations.RemoveField(
            model_name='shouter',
            name='ig_two_most_common_country',
        ),
        migrations.RemoveField(
            model_name='shouter',
            name='ig_two_most_common_gender_age',
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_audience_location_1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='AUDIENCE LOCATION #1'),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_audience_location_1_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='AUDIENCE LOCATION #1 PERCENT'),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_audience_location_2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='AUDIENCE LOCATION #2'),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_audience_location_2_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='AUDIENCE LOCATION #2 PERCENT'),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_audience_undefined_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='AUDIENCE UNDEFINED'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_age_range_13_17',
            field=models.FloatField(blank=True, null=True, verbose_name='AUDIENCE 13-17'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_age_range_18_24',
            field=models.FloatField(blank=True, null=True, verbose_name='AUDIENCE 18-24'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_age_range_25_34',
            field=models.FloatField(blank=True, null=True, verbose_name='AUDIENCE 25-34'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_age_range_35_44',
            field=models.FloatField(blank=True, null=True, verbose_name='AUDIENCE 35-44'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_age_range_45_54',
            field=models.FloatField(blank=True, null=True, verbose_name='AUDIENCE 45-54'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_age_range_55_64',
            field=models.FloatField(blank=True, null=True, verbose_name='AUDIENCE 55-64'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_audience_female_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='AUDIENCE FEMALE'),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='ig_audience_male_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='AUDIENCE MALE'),
        ),
    ]
