# Generated by Django 3.2.9 on 2021-12-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0011_auto_20211219_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shouter',
            old_name='is_check_ig',
            new_name='is_check_ig_fb_post',
        ),
        migrations.RenameField(
            model_name='shouter',
            old_name='is_check_ig_fb',
            new_name='is_check_ig_fb_story',
        ),
        migrations.AddField(
            model_name='shouter',
            name='is_check_ig_fb_story_post',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='is_check_ig_post',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='is_check_ig_story',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='is_check_ig_story_post',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='tiktok_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='twitter_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
