# Generated by Django 3.2.9 on 2022-08-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0012_auto_20220822_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouter',
            name='is_insight',
            field=models.BooleanField(default=False, verbose_name='IS INSIGHT DATA'),
        ),
    ]
