# Generated by Django 3.2.9 on 2021-12-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0012_auto_20211219_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouter',
            name='is_check_ig',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='is_check_ig_fb',
            field=models.BooleanField(default=True),
        ),
    ]
