# Generated by Django 3.2.9 on 2021-12-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0013_auto_20211219_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouter',
            name='tiktok_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shouter',
            name='twitter_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
