# Generated by Django 3.2.9 on 2022-08-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0013_shouter_is_insight'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouter',
            name='ig_profile_picture_file',
            field=models.ImageField(blank=True, null=True, upload_to='instagram/profile/'),
        ),
    ]
