# Generated by Django 3.2.9 on 2022-08-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0014_shouter_ig_profile_picture_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouter',
            name='ig_media_picture_1',
            field=models.ImageField(blank=True, null=True, upload_to='instagram/media/'),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_media_picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='instagram/media/'),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_media_picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='instagram/media/'),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_media_picture_4',
            field=models.ImageField(blank=True, null=True, upload_to='instagram/media/'),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_media_picture_5',
            field=models.ImageField(blank=True, null=True, upload_to='instagram/media/'),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_media_picture_6',
            field=models.ImageField(blank=True, null=True, upload_to='instagram/media/'),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_media_picture_7',
            field=models.ImageField(blank=True, null=True, upload_to='instagram/media/'),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_media_picture_8',
            field=models.ImageField(blank=True, null=True, upload_to='instagram/media/'),
        ),
        migrations.AddField(
            model_name='shouter',
            name='ig_media_picture_9',
            field=models.ImageField(blank=True, null=True, upload_to='instagram/media/'),
        ),
    ]
