# Generated by Django 3.2.9 on 2021-12-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouters', '0014_auto_20211219_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shouter',
            name='is_check_ig',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_check_ig_fb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_check_ig_fb_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_check_ig_fb_story',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_check_ig_fb_story_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_check_ig_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_check_ig_story',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shouter',
            name='is_check_ig_story_post',
            field=models.BooleanField(default=False),
        ),
    ]
