# Generated by Django 3.2.9 on 2022-08-30 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0022_campaign_service_type'),
        ('shouters', '0015_auto_20220825_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False)),
                ('brand_price', models.IntegerField(blank=True, null=True)),
                ('shouter_price', models.IntegerField(blank=True, null=True)),
                ('cpr', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('ig_follower_count', models.IntegerField(blank=True, null=True)),
                ('ig_following_count', models.IntegerField(blank=True, null=True)),
                ('ig_media_count', models.IntegerField(blank=True, null=True)),
                ('ig_engagement_percent', models.FloatField(blank=True, null=True, verbose_name='IG => LIKE PERCENTAGE')),
                ('ig_active_follower', models.IntegerField(blank=True, null=True)),
                ('ig_average_total_like', models.IntegerField(blank=True, null=True, verbose_name='IG => AVERAGE LIKE')),
                ('ig_story_view', models.IntegerField(blank=True, null=True, verbose_name='IG => AVERAGE STORY VIEW')),
                ('ig_ad_post_reach', models.IntegerField(blank=True, null=True, verbose_name='FINAL => EST AD POST REACH')),
                ('ig_audience_male_percent', models.FloatField(blank=True, null=True, verbose_name='AUDIENCE MALE')),
                ('ig_audience_female_percent', models.FloatField(blank=True, null=True, verbose_name='AUDIENCE FEMALE')),
                ('ig_audience_undefined_percent', models.FloatField(blank=True, null=True, verbose_name='AUDIENCE UNDEFINED')),
                ('ig_age_range_13_17', models.FloatField(blank=True, null=True, verbose_name='AUDIENCE 13-17')),
                ('ig_age_range_18_24', models.FloatField(blank=True, null=True, verbose_name='AUDIENCE 18-24')),
                ('ig_age_range_25_34', models.FloatField(blank=True, null=True, verbose_name='AUDIENCE 25-34')),
                ('ig_age_range_35_44', models.FloatField(blank=True, null=True, verbose_name='AUDIENCE 35-44')),
                ('ig_age_range_45_54', models.FloatField(blank=True, null=True, verbose_name='AUDIENCE 45-54')),
                ('ig_age_range_55_64', models.FloatField(blank=True, null=True, verbose_name='AUDIENCE 55-64')),
                ('ig_audience_location_1', models.CharField(blank=True, max_length=120, null=True, verbose_name='AUDIENCE LOCATION #1')),
                ('ig_audience_location_1_percent', models.FloatField(blank=True, null=True, verbose_name='AUDIENCE LOCATION #1 PERCENT')),
                ('ig_audience_location_2', models.CharField(blank=True, max_length=120, null=True, verbose_name='AUDIENCE LOCATION #2')),
                ('ig_audience_location_2_percent', models.FloatField(blank=True, null=True, verbose_name='AUDIENCE LOCATION #2 PERCENT')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('shouter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shouters.shouter')),
            ],
        ),
    ]
